[env]
# all workspace members can use this Makefile
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
PORT = "8000"

# ---- BUILD & CREATE WASMS ----
[tasks.build_debug]
description = "Build"
workspace = false
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown"]

[tasks.build_release]
description = "Build, with the --release flag"
workspace = false
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.create_wasm_debug]
description = "Build with wasm debug"
command = "wasm-bindgen"
dependencies = ["build_debug"]
args = ["target/wasm32-unknown-unknown/debug/shower_frontend.wasm", "--no-typescript", "--target", "web", "--out-dir", "./pkg", "--out-name", "package"]

[tasks.create_wasm_release]
description = "Build with wasm release"
command = "wasm-bindgen"
dependencies = ["build_release"]
args = ["target/wasm32-unknown-unknown/release/shower_frontend.wasm", "--no-typescript", "--target", "web", "--out-dir", "./pkg", "--out-name", "package"]

[tasks.all]
description = "Build, and create wasms"
workspace = false
dependencies = ["build", "create_wasm"]

[tasks.watch]
description = "Build, create wasms, and watch/recompile files for changes"
workspace = false
dependencies = ["create_wasm_debug"]
watch = { ignore_pattern="pkg/*" }


[tasks.watch_and_serve]
 description = "Build, create wasms, and watch/recompile files for changes"
 workspace = false
 #dependencies = ["create_wasm_release", "serve"]
 script = [
 '''
     echo running script
     (trap 'kill 0' SIGINT; cargo make watch & cargo make serve)
 '''
 ]


[tasks.all_release]
description = "Build, and create wasms, with the --release flag"
workspace = false
dependencies = ["build_release", "create_wasm_release"]

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
workspace = false
command = "microserver"
args = ["--port", "${PORT}"]

